# Site settings
title: astomusic
email: astomusic@naver.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://astomusic.github.io" # the base hostname & protocol for your site
twitter_username: astomusic
github_username:  astomusic

paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
